user:
  $ref: parameters/user.yaml

register:
  $ref: parameters/register.yaml

user_id:
  $ref: parameters/user_id.yaml

block_id:
  $ref: parameters/block_id.yaml

friend_id:
  $ref: parameters/friend_id.yaml

subscribe_id:
  $ref: parameters/subscribe_id.yaml

avatar:
  $ref: parameters/avatar.yaml


stream:
  $ref: parameters/stream.yaml

stream_id:
  $ref: parameters/stream_id.yaml


organization:
  $ref: parameters/organization.yaml

organization_id:
  $ref: parameters/organization_id.yaml


start:
  $ref: parameters/start.yaml

limit:
  $ref: parameters/limit.yaml


tag:
  $ref: parameters/tag.yaml

tag_id:
  $ref: parameters/tag_id.yaml


login:
  $ref: parameters/login.yaml


jwt:
  $ref: parameters/jwt.yaml
